name:                text-via-sockets
version:             0.1.0.0
github:              "capitanbatata/text-via-sockets"
license:             BSD3
author:              "Damian Nadales"
maintainer:          "damian.nadales@gmail.com"
copyright:           "Copyright: (c) 2017 Damian Nadales"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Send and receive text lines using sockets.
category:            Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/capitanbatata/text-via-sockets#readme>


# Shared dependencies across library, benchmarks, and tests.
dependencies:
  - base >= 4.7 && < 5
  - network

library:
  source-dirs: src
  dependencies:
    - bytestring
    - stm
    - NoTrace
    - retry
    - exceptions
    - text

ghc-options:
  - -O
  - -Werror
  - -Wall

default-extensions:
- OverloadedStrings

flags:
  debug:
    description: Enable debug
    manual: True
    default: False

when:
  - condition: flag(debug)
    cpp-options:  -DDEBUG

tests:
  text-via-sockets-test:
    main:                Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -O
    dependencies:
    - hspec
    - QuickCheck
    - quickcheck-text
    - async
    - NoTrace
    - text    
    - text-via-sockets

  no-resources-leak-test:
    main:                Main.hs
    source-dirs:
    - test/endurance/no-resources-leak
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    - -Werror
    - -Wall
    - -O
    dependencies:
    - async
    - ekg

    - text-via-sockets


benchmarks:
  text-via-sockets-bench:
    main: Main.hs
    source-dirs:
      - bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -O
    dependencies:
    - criterion
    - async
    - text

    - text-via-sockets
